/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/chalkboard.glb -t 
Author: FrodoUndead (https://sketchfab.com/FrodoUndead)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chalkboard-7ca01a2834384d1a9205e2919a7acb30
Title: Chalkboard
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ApiResponse } from '@/app/page'
import Question from '../Question'
import Answer from '../Answer'
import Progress from '../Progress'
import Timer from '../Timer'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

interface Props {
  items: ApiResponse
}


// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Chalkboard({ items, ...props }: Props & JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/chalkboard.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} rotation={[0, 0, 0]}>
          <Html
            //  occlude
             transform
             scale={0.3}
             className='max-w-[690px] relative px-2 h-[420px]'
             position={[-0.,0.,0.04]}
          >
            
            <div className='text-center absolute top-6 left-1/2 -translate-x-1/2'>
              <Progress data={items} />
            </div>

            <div className='w-full h-full grid grid-cols-12 '>
              <div className="col-span-6 my-auto">
                <Answer items={items} />
              </div>
              <div className='col-span-6 py-32'>
                <Question items={items} />
              </div>
            </div>
          </Html>

          {/* <Html
            as='div'
            transform
            position={[-1.2,-0.0,0.04]}
          >
            <Progress data={items} />
          </Html>

          <Html 
          as='div'
          className='max-w-[320px]'
          transform
          scale={0.3}
          position={[-1.2,-0.0,0.04]}
          >
            <Answer items={items} />
          </Html> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/chalkboard.glb')
